// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: gateway/proto/catalog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Catalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_gateway_proto_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_gateway_proto_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Catalog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Catalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Catalog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Catalog) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatalogRequest) Reset() {
	*x = CreateCatalogRequest{}
	mi := &file_gateway_proto_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogRequest) ProtoMessage() {}

func (x *CreateCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogRequest.ProtoReflect.Descriptor instead.
func (*CreateCatalogRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCatalogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCatalogRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCatalogRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       *Catalog               `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatalogResponse) Reset() {
	*x = CreateCatalogResponse{}
	mi := &file_gateway_proto_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogResponse) ProtoMessage() {}

func (x *CreateCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogResponse.ProtoReflect.Descriptor instead.
func (*CreateCatalogResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCatalogResponse) GetCatalog() *Catalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

type GetCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogRequest) Reset() {
	*x = GetCatalogRequest{}
	mi := &file_gateway_proto_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRequest) ProtoMessage() {}

func (x *GetCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetCatalogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       *Catalog               `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogResponse) Reset() {
	*x = GetCatalogResponse{}
	mi := &file_gateway_proto_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogResponse) ProtoMessage() {}

func (x *GetCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetCatalogResponse) GetCatalog() *Catalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

type GetCatalogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogsRequest) Reset() {
	*x = GetCatalogsRequest{}
	mi := &file_gateway_proto_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogsRequest) ProtoMessage() {}

func (x *GetCatalogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogsRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetCatalogsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetCatalogsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCatalogsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetCatalogsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetCatalogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalogs      []*Catalog             `protobuf:"bytes,1,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogsResponse) Reset() {
	*x = GetCatalogsResponse{}
	mi := &file_gateway_proto_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogsResponse) ProtoMessage() {}

func (x *GetCatalogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogsResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetCatalogsResponse) GetCatalogs() []*Catalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

var File_gateway_proto_catalog_proto protoreflect.FileDescriptor

const file_gateway_proto_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1bgateway/proto/catalog.proto\x12\acatalog\"e\n" +
	"\aCatalog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"b\n" +
	"\x14CreateCatalogRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"C\n" +
	"\x15CreateCatalogResponse\x12*\n" +
	"\acatalog\x18\x01 \x01(\v2\x10.catalog.CatalogR\acatalog\"#\n" +
	"\x11GetCatalogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetCatalogResponse\x12*\n" +
	"\acatalog\x18\x01 \x01(\v2\x10.catalog.CatalogR\acatalog\"j\n" +
	"\x12GetCatalogsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\"C\n" +
	"\x13GetCatalogsResponse\x12,\n" +
	"\bcatalogs\x18\x01 \x03(\v2\x10.catalog.CatalogR\bcatalogs2\xf5\x01\n" +
	"\x0eCatalogService\x12N\n" +
	"\rCreateCatalog\x12\x1d.catalog.CreateCatalogRequest\x1a\x1e.catalog.CreateCatalogResponse\x12I\n" +
	"\x0eGetCatalogById\x12\x1a.catalog.GetCatalogRequest\x1a\x1b.catalog.GetCatalogResponse\x12H\n" +
	"\vGetCatalogs\x12\x1b.catalog.GetCatalogsRequest\x1a\x1c.catalog.GetCatalogsResponseB\x0fZ\rgateway/protob\x06proto3"

var (
	file_gateway_proto_catalog_proto_rawDescOnce sync.Once
	file_gateway_proto_catalog_proto_rawDescData []byte
)

func file_gateway_proto_catalog_proto_rawDescGZIP() []byte {
	file_gateway_proto_catalog_proto_rawDescOnce.Do(func() {
		file_gateway_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_catalog_proto_rawDesc), len(file_gateway_proto_catalog_proto_rawDesc)))
	})
	return file_gateway_proto_catalog_proto_rawDescData
}

var file_gateway_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gateway_proto_catalog_proto_goTypes = []any{
	(*Catalog)(nil),               // 0: catalog.Catalog
	(*CreateCatalogRequest)(nil),  // 1: catalog.CreateCatalogRequest
	(*CreateCatalogResponse)(nil), // 2: catalog.CreateCatalogResponse
	(*GetCatalogRequest)(nil),     // 3: catalog.GetCatalogRequest
	(*GetCatalogResponse)(nil),    // 4: catalog.GetCatalogResponse
	(*GetCatalogsRequest)(nil),    // 5: catalog.GetCatalogsRequest
	(*GetCatalogsResponse)(nil),   // 6: catalog.GetCatalogsResponse
}
var file_gateway_proto_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.CreateCatalogResponse.catalog:type_name -> catalog.Catalog
	0, // 1: catalog.GetCatalogResponse.catalog:type_name -> catalog.Catalog
	0, // 2: catalog.GetCatalogsResponse.catalogs:type_name -> catalog.Catalog
	1, // 3: catalog.CatalogService.CreateCatalog:input_type -> catalog.CreateCatalogRequest
	3, // 4: catalog.CatalogService.GetCatalogById:input_type -> catalog.GetCatalogRequest
	5, // 5: catalog.CatalogService.GetCatalogs:input_type -> catalog.GetCatalogsRequest
	2, // 6: catalog.CatalogService.CreateCatalog:output_type -> catalog.CreateCatalogResponse
	4, // 7: catalog.CatalogService.GetCatalogById:output_type -> catalog.GetCatalogResponse
	6, // 8: catalog.CatalogService.GetCatalogs:output_type -> catalog.GetCatalogsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_proto_catalog_proto_init() }
func file_gateway_proto_catalog_proto_init() {
	if File_gateway_proto_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_catalog_proto_rawDesc), len(file_gateway_proto_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_catalog_proto_goTypes,
		DependencyIndexes: file_gateway_proto_catalog_proto_depIdxs,
		MessageInfos:      file_gateway_proto_catalog_proto_msgTypes,
	}.Build()
	File_gateway_proto_catalog_proto = out.File
	file_gateway_proto_catalog_proto_goTypes = nil
	file_gateway_proto_catalog_proto_depIdxs = nil
}
