// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: gateway/proto/order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     []byte                 `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	Catalogs      []*Order_OrderCatalog  `protobuf:"bytes,5,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_gateway_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_gateway_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetCreatedAt() []byte {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetCatalogs() []*Order_OrderCatalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	AccountId     string                             `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Catalogs      []*CreateOrderRequest_OrderCatalog `protobuf:"bytes,4,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_gateway_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateOrderRequest) GetCatalogs() []*CreateOrderRequest_OrderCatalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_gateway_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_gateway_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_gateway_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrdersForAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersForAccountRequest) Reset() {
	*x = GetOrdersForAccountRequest{}
	mi := &file_gateway_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersForAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersForAccountRequest) ProtoMessage() {}

func (x *GetOrdersForAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersForAccountRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersForAccountRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrdersForAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetOrdersForAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersForAccountResponse) Reset() {
	*x = GetOrdersForAccountResponse{}
	mi := &file_gateway_proto_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersForAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersForAccountResponse) ProtoMessage() {}

func (x *GetOrdersForAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersForAccountResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersForAccountResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrdersForAccountResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Order_OrderCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint32                 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order_OrderCatalog) Reset() {
	*x = Order_OrderCatalog{}
	mi := &file_gateway_proto_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order_OrderCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_OrderCatalog) ProtoMessage() {}

func (x *Order_OrderCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_OrderCatalog.ProtoReflect.Descriptor instead.
func (*Order_OrderCatalog) Descriptor() ([]byte, []int) {
	return file_gateway_proto_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Order_OrderCatalog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order_OrderCatalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Order_OrderCatalog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Order_OrderCatalog) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order_OrderCatalog) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequest_OrderCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogId     string                 `protobuf:"bytes,2,opt,name=catalogId,proto3" json:"catalogId,omitempty"`
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest_OrderCatalog) Reset() {
	*x = CreateOrderRequest_OrderCatalog{}
	mi := &file_gateway_proto_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest_OrderCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest_OrderCatalog) ProtoMessage() {}

func (x *CreateOrderRequest_OrderCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest_OrderCatalog.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest_OrderCatalog) Descriptor() ([]byte, []int) {
	return file_gateway_proto_order_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateOrderRequest_OrderCatalog) GetCatalogId() string {
	if x != nil {
		return x.CatalogId
	}
	return ""
}

func (x *CreateOrderRequest_OrderCatalog) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_gateway_proto_order_proto protoreflect.FileDescriptor

const file_gateway_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/proto/order.proto\x12\x05order\"\xb3\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\fR\tcreatedAt\x12\x1c\n" +
	"\taccountId\x18\x03 \x01(\tR\taccountId\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x04 \x01(\x01R\n" +
	"totalPrice\x125\n" +
	"\bcatalogs\x18\x05 \x03(\v2\x19.order.Order.OrderCatalogR\bcatalogs\x1a\x86\x01\n" +
	"\fOrderCatalog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\rR\bquantity\"\xc0\x01\n" +
	"\x12CreateOrderRequest\x12\x1c\n" +
	"\taccountId\x18\x02 \x01(\tR\taccountId\x12B\n" +
	"\bcatalogs\x18\x04 \x03(\v2&.order.CreateOrderRequest.OrderCatalogR\bcatalogs\x1aH\n" +
	"\fOrderCatalog\x12\x1c\n" +
	"\tcatalogId\x18\x02 \x01(\tR\tcatalogId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\"9\n" +
	"\x13CreateOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x10GetOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\":\n" +
	"\x1aGetOrdersForAccountRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\tR\taccountId\"C\n" +
	"\x1bGetOrdersForAccountResponse\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.order.OrderR\x06orders2\xb6\x01\n" +
	"\fOrderService\x12F\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\"\x00\x12^\n" +
	"\x13GetOrdersForAccount\x12!.order.GetOrdersForAccountRequest\x1a\".order.GetOrdersForAccountResponse\"\x00B\x0fZ\rgateway/protob\x06proto3"

var (
	file_gateway_proto_order_proto_rawDescOnce sync.Once
	file_gateway_proto_order_proto_rawDescData []byte
)

func file_gateway_proto_order_proto_rawDescGZIP() []byte {
	file_gateway_proto_order_proto_rawDescOnce.Do(func() {
		file_gateway_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_order_proto_rawDesc), len(file_gateway_proto_order_proto_rawDesc)))
	})
	return file_gateway_proto_order_proto_rawDescData
}

var file_gateway_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gateway_proto_order_proto_goTypes = []any{
	(*Order)(nil),                           // 0: order.Order
	(*CreateOrderRequest)(nil),              // 1: order.CreateOrderRequest
	(*CreateOrderResponse)(nil),             // 2: order.CreateOrderResponse
	(*GetOrderRequest)(nil),                 // 3: order.GetOrderRequest
	(*GetOrderResponse)(nil),                // 4: order.GetOrderResponse
	(*GetOrdersForAccountRequest)(nil),      // 5: order.GetOrdersForAccountRequest
	(*GetOrdersForAccountResponse)(nil),     // 6: order.GetOrdersForAccountResponse
	(*Order_OrderCatalog)(nil),              // 7: order.Order.OrderCatalog
	(*CreateOrderRequest_OrderCatalog)(nil), // 8: order.CreateOrderRequest.OrderCatalog
}
var file_gateway_proto_order_proto_depIdxs = []int32{
	7, // 0: order.Order.catalogs:type_name -> order.Order.OrderCatalog
	8, // 1: order.CreateOrderRequest.catalogs:type_name -> order.CreateOrderRequest.OrderCatalog
	0, // 2: order.CreateOrderResponse.order:type_name -> order.Order
	0, // 3: order.GetOrderResponse.order:type_name -> order.Order
	0, // 4: order.GetOrdersForAccountResponse.orders:type_name -> order.Order
	1, // 5: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	5, // 6: order.OrderService.GetOrdersForAccount:input_type -> order.GetOrdersForAccountRequest
	2, // 7: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	6, // 8: order.OrderService.GetOrdersForAccount:output_type -> order.GetOrdersForAccountResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gateway_proto_order_proto_init() }
func file_gateway_proto_order_proto_init() {
	if File_gateway_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_order_proto_rawDesc), len(file_gateway_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_order_proto_goTypes,
		DependencyIndexes: file_gateway_proto_order_proto_depIdxs,
		MessageInfos:      file_gateway_proto_order_proto_msgTypes,
	}.Build()
	File_gateway_proto_order_proto = out.File
	file_gateway_proto_order_proto_goTypes = nil
	file_gateway_proto_order_proto_depIdxs = nil
}
